//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenceRegistrationClient.AbsenceRegistrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AbsenceRegistrationService.IAbsenceRegistration")]
    public interface IAbsenceRegistration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbsenceRegistration/CreateUser", ReplyAction="http://tempuri.org/IAbsenceRegistration/CreateUserResponse")]
        void CreateUser(string email, string fisrtname, string surname, string password, string confirmPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbsenceRegistration/CreateUser", ReplyAction="http://tempuri.org/IAbsenceRegistration/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string email, string fisrtname, string surname, string password, string confirmPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbsenceRegistration/LoginUser", ReplyAction="http://tempuri.org/IAbsenceRegistration/LoginUserResponse")]
        void LoginUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbsenceRegistration/LoginUser", ReplyAction="http://tempuri.org/IAbsenceRegistration/LoginUserResponse")]
        System.Threading.Tasks.Task LoginUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbsenceRegistration/CheckIn", ReplyAction="http://tempuri.org/IAbsenceRegistration/CheckInResponse")]
        void CheckIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbsenceRegistration/CheckIn", ReplyAction="http://tempuri.org/IAbsenceRegistration/CheckInResponse")]
        System.Threading.Tasks.Task CheckInAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAbsenceRegistrationChannel : AbsenceRegistrationClient.AbsenceRegistrationService.IAbsenceRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AbsenceRegistrationClient : System.ServiceModel.ClientBase<AbsenceRegistrationClient.AbsenceRegistrationService.IAbsenceRegistration>, AbsenceRegistrationClient.AbsenceRegistrationService.IAbsenceRegistration {
        
        public AbsenceRegistrationClient() {
        }
        
        public AbsenceRegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AbsenceRegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbsenceRegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbsenceRegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateUser(string email, string fisrtname, string surname, string password, string confirmPassword) {
            base.Channel.CreateUser(email, fisrtname, surname, password, confirmPassword);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string email, string fisrtname, string surname, string password, string confirmPassword) {
            return base.Channel.CreateUserAsync(email, fisrtname, surname, password, confirmPassword);
        }
        
        public void LoginUser(string email, string password) {
            base.Channel.LoginUser(email, password);
        }
        
        public System.Threading.Tasks.Task LoginUserAsync(string email, string password) {
            return base.Channel.LoginUserAsync(email, password);
        }
        
        public void CheckIn() {
            base.Channel.CheckIn();
        }
        
        public System.Threading.Tasks.Task CheckInAsync() {
            return base.Channel.CheckInAsync();
        }
    }
}
